FROM caddy:2-builder AS builder

ENV GOPROXY=https://goproxy.io,direct

RUN xcaddy build \
    --with github.com/mholt/caddy-ratelimit \
    --with github.com/pberkel/caddy-storage-redis

FROM caddy:2

COPY --from=builder /usr/bin/caddy /usr/bin/caddy